name: Build Linux VST3

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libasound2-dev libjack-jackd2-dev libfreetype6-dev libx11-dev libxcomposite-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev build-essential

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DJUCE_BUILD_LV2=OFF

      - name: Build
        run: cmake --build build --config Release -- -j $(nproc)

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Mayerism-Linux-VST3
          path: build/**/*_artefacts/Release/VST3/*.vst3
